# Generated by Django 4.0.5 on 2022-06-15 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jogo', '0001_initial'),
        ('Administracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_da_venda', models.DateTimeField()),
                ('Preco', models.FloatField()),
                ('Jogovendido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jogo.jogo')),
                ('Venda_Realizada_Por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracao.funcionario')),
            ],
        ),
    ]
