# Generated by Django 4.0.5 on 2022-06-15 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0001_initial'),
        ('Venda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='Metodo_de_Pagamento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Administracao.pagamento'),
            preserve_default=False,
        ),
    ]
