# Generated by Django 4.0.5 on 2022-06-15 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0001_initial'),
        ('Venda', '0002_venda_metodo_de_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='Nome_Cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Administracao.cliente'),
            preserve_default=False,
        ),
    ]
