# Generated by Django 4.0.5 on 2022-06-15 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_jogo', models.CharField(max_length=100)),
                ('data_de_lancamento', models.DateField()),
                ('sinopse', models.TextField()),
                ('preco', models.FloatField()),
                ('estoque_atual', models.PositiveSmallIntegerField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracao.genero')),
            ],
        ),
    ]
