# Generated by Django 4.0.5 on 2022-06-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
